### ISSUE TITLE
Nicer error messages

### ISSUE THREAD

**Issue by gaborcsardi** [gaborcsardi/argufy#1]
Maybe look at `assertthat`. Maybe we can even use `assertthat`.

**Comment by gaborcsardi** [comment]
Options:
1. Copy over stuff from `assertthat`. Not really a good approach in general.
2. Make `argufy` recognize `assertthat` assertions (they have a `fail` attribute), so that one can just write
   
   ``` r
   argufy(function(x = ~ not_empty))
   ```

I would still like to add other assertions, and I am not sure where these would go. Maybe put the assertions into a separate package, and reexport (some? all?) assertions from assertthat?

**Comment by jimhester** [comment]
Maybe an even easier method would be to make `stopifnot` a user specified parameter to `get_check_expr`, then people could use whatever function they would like.

e.g.

``` r
get_check_expr <- function(check, fun = stopifnot) {
  fun <- as.name(deparse(substitute(fun)))

  if (is_check_function(check)) {
    substitute(
      `__fun__`(`_check_`(`_name_`)),
      list(`__fun__` = fun, `_check_` = check$check, `_name_` = as.name(check$name))
    )
  } else if (is_coercion_function(check)) {
    substitute(
      `_name_` <- `_coerce_`(`_name_`),
      list(`_coerce_` = check$check, `_name_` = as.name(check$name))
    )
  } else if (is.null(check$check)) {
    NULL
  } else {
    substitute(
      `__fun__`(`_expr_`),
      list(`__fun__` = fun, `_expr_` = check$check)
    )
  }
}
```

The above doesn't quite work perfectly, loading `library(assertthat)`, then passing `fun = assert_that` works, but `fun = assertthat::assert_that` tries to substitute `assertthat::assert_that` as the full function name rather than constructing a call to `::`.

**Comment by gaborcsardi** [comment]
I don't mind making things configurable in general. I think it is simpler if `fun` is just a function, and you don't do NSE at all. We can use the `pkgconfig` package for this, so that packages do not interfere.

But maybe this is overkill for now. Why don't we just make the default nicer? I think I'll just import `assertthat`.

**Comment by jimhester** [comment]
https://github.com/mllg/checkmate supplies a lot of various argument checking functions as well, we might want to look at playing nicely with that if possible.

**Comment by gaborcsardi** [comment]
We could use your code in https://github.com/gaborcsardi/argufy/issues/1#issuecomment-129897670 to support `checkmate`.

Maybe we can also support it out of the box, i.e. detect if the assertion is a `checkmate` call, and omit the `stopifnot`.

Similarly for http://www.r-pkg.org/pkg/assertive and http://www.r-pkg.org/pkg/ensurer.

We can also make `assert_that` the default, instead of `stopifnot`.
