### ISSUE TITLE
R CMD check failures

### ISSUE THREAD

**Issue by gaborcsardi** [gaborcsardi/argufy#10]
In `disposables` the `argufy` package cannot be loaded while installing, because the install runs in a separate R process. We need to make the package that runs the tests is available in this R process.

More precisely, the problem is that `argufy` is a build-time dependency of the tested disposable packages. This comes up often, and probably should be supported by `disposables`.

**Comment by jimhester** [comment]
Ah you are correct, removing `argufy` from the package library and restarting R results in failures running `devtools::test()` and `devtools::check()`.  Interestingly `R CMD check` works fine regardless as I believe it installs the package being checked prior to running the tests.

**Comment by gaborcsardi** [comment]
Yeah, so `R CMD check` installs the package being tested somewhere, we just need to query where, and add that path to `.libPaths()` temporarily.

**Comment by gaborcsardi** [comment]
@jimhester I am not sure actually what you mean by `R CMD check` working fine. :) It gives errors for me.... maybe it depends on your R config and where your packages are loaded from.

**Comment by gaborcsardi** [comment]
@jimhester Forget it, I know what you meant.

**Comment by jimhester** [comment]
You have probably figured this out, `R CMD check` alone passes the tests, `R CMD check --as-cran` fails them.

**Comment by gaborcsardi** [comment]
Yeah, I am not sure what exactly happens, though. Maybe `R CMD check --as-cran` creates a new library. Anyway, this is definitely solvable, and probably should be solved/supported in `disposables`.

**Comment by gaborcsardi** [comment]
OK, I am an idiot. `disposables::make_packages` has an `imports` argument, for exactly this reason. We just need to supply `imports = "argufy"` and then it all works fine. I can't remember I forgot this......

**Comment by jimhester** [comment]
Yep that fixed it on my end.  Something weird is definitely going on in `R CMD check` but trying to decipher the 4800 line [tools::.check_packages()](https://github.com/wch/r-source/blob/trunk/src/library/tools/R/check.R#L174-L4822) is giving me a headache and probably isn't worth figuring out anyway.
