### ISSUE TITLE
Coverage not being uploaded

### ISSUE THREAD

**Issue by jimhester** [gaborcsardi/argufy#16]
I don't think this actually a bug in the argufy setup, just putting it here for convenience. 

The coverage reports aren't being uploaded to codecov (https://travis-ci.org/gaborcsardi/argufy/jobs/75725712#L2136-L2148), I think because r-builder does matrix builds and codecov does not handle them properly.
- [x] see if codecov is supposed to handle matrix builds on travis
- [x] if codecov doesn't support matrix builds, explicitly set the codcov token, which should fix this issue
- [x] coverage only needs to run on one of the matrix builds, probably devel

**Comment by gaborcsardi** [comment]
Yes, I actually wanted to note this when you added coverage. I mean that it is fine if we run it in r-devel. Or r-relese, it does not really matter.

**Comment by gaborcsardi** [comment]
OK, seemingly all is well here, I fixed r-builder for r-devel.
