### ISSUE TITLE
Feature request: Inject type information into roxygen documentation

### ISSUE THREAD

**Issue by krlmlr** [gaborcsardi/argufy#18]
I like the explicit documentation of argument types, e.g., in [BatchJobs](http://www.rdocumentation.org/packages/BatchJobs/functions/makeRegistry). Would you support generating this automatically from the argufy argument specifications? Not sure what's the best way to implement such a feature.

**Comment by gaborcsardi** [comment]
I very much like this idea, but I don't see how it would be possible without either having a Roxygen preprocessor or built-in support for it in Roxygen. The latter is better for users, obviously, but it will not happen unless masses start using `argufy`, which is unlikely.

**Comment by krlmlr** [comment]
It's a pity that the preref parsers in roxygen2 [don't seem to have access](https://github.com/klutometis/roxygen/blob/a92178c184106c6e4d61afa73b3f903b25f69833/R/parse-preref.R#L38) to the [object to which the documentation refers](https://github.com/klutometis/roxygen/blob/a92178c184106c6e4d61afa73b3f903b25f69833/R/parse.R#L34-L37) -- but perhaps this can be changed?

**Comment by gaborcsardi** [comment]
This is a very good idea. I am rewriting that code in roxygen actually, for maxygen, and could add this as well: https://github.com/klutometis/roxygen/pull/370

**Comment by krlmlr** [comment]
This would be really great -- I could use that for `import.gen`, too. We might need to start looking into chaining and uninstalling preref parsers :-o

**Comment by gaborcsardi** [comment]
With the new syntax and implementation, this is automatic. From this:

``` r
#' Prefix of a string
#'
#' @param str \assert{is.character(str)} Character vector.
#' @param len \assert{is.integer(len)} Integer vector.
#' @return Prefix is string, of prescribed length.

prefix <- function(str, len) {
  substring(str, 1, len)
}
```

you get this in the manual:

```
Arguments:
     str: [‘is.character(str)’] Character vector.
     len: [‘is.integer(len)’] Integer vector.
```

Although the example is kind of stupid, because the textual description states the same as the assertion...
