### ISSUE TITLE
assertions on defaults

### ISSUE THREAD

**Issue by lawremi** [gaborcsardi/argufy#23]
Might consider always checking assertions, unless the argument is somehow marked as optional, i.e., where missingness is meaningful and explicitly allowed. Even if there is a default value, it's safest to run the assertion, just to check the code. At the very least, there should be an option for always checking, because, for example, right now `?~ as_enum` will not properly resolve the default case, unless the client calls `match.arg` on its own. This breaks e.g. `gmailr::message()`.

**Comment by gaborcsardi** [comment]
I think we are always checking assertions right now. 

As for missing arguments, yes, maybe we could support this. We can come back to this after #21 is decided, I think.

**Comment by gaborcsardi** [comment]
Actually we are not checking the defaults now, as it turns out. I misremembered. But it would make sense to check them.

**Comment by gaborcsardi** [comment]
Skipping this for now, might come back to it later.
