### ISSUE TITLE
Devtools hook

### ISSUE THREAD

**Issue by gaborcsardi** [gaborcsardi/argufy#29]
Need to argufy functions when loading them via `devtools::load_all`.

**Comment by jimhester** [comment]
`load_all()` does call the packages `.onLoad()` functions, https://github.com/hadley/devtools/blob/master/R/load.r#L157, https://github.com/hadley/devtools/blob/81dd313e1d143a3bdaaa2e1f09c887801db66694/R/run-loadhooks.r#L37-L58, so if that is all that is needed it should work without changes.

**Comment by gaborcsardi** [comment]
Thanks, that's good. Some other changes are still needed, because in `.onLoad()` I add some hooks to base functions, and to minimize risks I only add them if .onLoad() is called while a package installation is in progress. So I need to similarly detect if a `devtools::load_all()` is in progress.

Also, currently I modify the functions just before putting them into the lazy load DB, and `load_all()` does not do that I guess, so we also need to find a good place to add the assertions.

**Comment by gaborcsardi** [comment]
Thanks, that's good. Some other changes are still needed, because in `.onLoad()` I add some hooks to base functions, and to minimize risks I only add them if .onLoad() is called while a package installation is in progress. So I need to similarly detect if a `devtools::load_all()` is in progress.

Also, currently I modify the functions just before putting them into the lazy load DB, and `load_all()` does not do that I guess, so we also need to find a good place to add the assertions.
