### ISSUE TITLE
Internal functions without an Rd file

### ISSUE THREAD

**Issue by gaborcsardi** [gaborcsardi/argufy#37]
Cannot be tested currently.... OK, one can do `\keywords internal` and have an Rd, but this is not optimal....

**Comment by gaborcsardi** [comment]
This is my major issue now......

**Comment by jimhester** [comment]
We could go back to _just_ using `?` and generate the appropriate .Rd annotations if documentation for the function exists (don't kill me please)

**Comment by gaborcsardi** [comment]
Hahahahah.

As you might suspect, I thought about this, too. However, I would need to rewrite all the code. Again. :) 

Which is fine, actually, not a big code base. And we could use the same install "hook", so that one would not need to call `argufy` explicitly.

But the `?` notation is also not optimal. I know it is best possible, but still.

**Comment by jimhester** [comment]
It is not perfect maybe, but it isn't too bad as `?` is really only used interactively.

Both approaches have their drawbacks I suppose, but either is an improvement over nothing :smile:.

**Comment by gaborcsardi** [comment]
Another issue with the `?` approach. One can put the assertion into the docs, yes, but in a manual page, an argument might belong to multiple functions. There is nothing that ensures that the checks are also put in for all these functions. It is possible to do some checking for them, maybe, but it looks tedious to have an install hook that essentially rewrites all code all documentation at the same time.

So I'll think about this a bit more.

**Comment by gaborcsardi** [comment]
E.g. how about keeping everything as it is :), and making sure that the internal incomplete manual pages still install OK:

``` r

#' @param list1 \assert{is.list}
#' @param list2 \assert{is.list}

merge_named_lists <- function(list1, list2, default = character()) {
  ...
}
```

Roxygen is fine with this of course, but it generates an Rd file without a title:

```
% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/utils.R
\name{merge_named_lists}
\alias{merge_named_lists}
\usage{
merge_named_lists(list1, list2, default = character())
}
\arguments{
\item{list1}{\assert{is.list}}

\item{list2}{\assert{is.list}}
}
```

and then you get an error at install time:

```
Error : /Users/gaborcsardi/works/mango/simplegraph/man/merge_named_lists.Rd:
Sections \title, and \name must exist and be unique in Rd files
ERROR: installing Rd objects failed for package ‘simplegraph’
```

So essentially all we need to do is adding 

```
\title{Internal function}
\keywords{internal}
```

to the Rd file, on the fly, while installing the package. (And the same while loading the package into `devtools` if we want to be pedantic.)

**Comment by gaborcsardi** [comment]
My main worry is that leaving out a title might be a mistake, and then `argufy` hides it. Maybe we can also check that the function is not in exported `NAMESPACE`. If it has no `title`, it is not exported, and it has assertions, then we assume that this is not an error, and the `@param` tags were added only to define the assertions. How does this sound?

**Comment by gaborcsardi** [comment]
OK, I will not overcomplicate this. :) If one wants assertions on internal functions, one needs to add `@keywords internal` and a title. This is not too bad I think. It is nice to have a short description for internal functions as well, after all.
