### ISSUE TITLE
Keep `?` notation as well?

### ISSUE THREAD

**Issue by gaborcsardi** [gaborcsardi/argufy#39]
Would you prefer that @jimhester ?

**Comment by jimhester** [comment]
Not sure if it is worth the added complexity it would require to keep.
Might also confuse people...

**Comment by gaborcsardi** [comment]
Yeah, I agree.

But I started using the package now, and find it really annoying that I don't have a good way to use it for internal functions, that do not have a manual page.... :(

**Comment by gaborcsardi** [comment]
Not keeping `?` notation then.
